name: Release

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: npm ci
            - name: Initlalize Git user
              run: |
                  git config user.name "Release Workflow"
                  git config user.email "yonghayden68@gmail.com"
            - name: "Run release"
              run: npm run release --ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
