name: Release
permissions:
    contents: read
    pull-requests: write
on: workflow_dispatch
jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install the dependencies
              run: npm ci
            - name: Initialize Git user
              run: git config --global user.email "yonghayden68@gmail.com"
                  git config --global user.name "Release Workflow"
            - name: End message
              run: echo "Completed Release workflow"
